FROM	debian:buster

RUN	apt-get update && apt-get upgrade -y && \
	apt-get install -y \
	mariadb-server

COPY	./conf/mariadb_setup.sh ./mariadb_setup.sh
COPY	./conf/db_setting.sql ./db_setting.sql

EXPOSE	3306

ENTRYPOINT	["bash", "mariadb_setup.sh"]
