FROM	debian:buster

RUN	apt-get update && apt-get upgrade -y && \
	apt-get install -y \
	mariadb-server

COPY	./conf/50-server.cnf /etc/mysql/mariadb.conf.d/
COPY	./tools/mariadb_setup.sh ./mariadb_setup.sh

EXPOSE	3306

ENTRYPOINT ["bash", "mariadb_setup.sh"]
