version: '3'

services:
  nginx:
    # Dockerfile이 있는 위치
    build: ./requirements/nginx/
    # 컨테이너 외부 개방 (포트 바인딩)
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/html
    networks:
      - docker-network

  mariadb:
    build: ./requirements/mariadb/
    # 컨테이너 내부 개방
    expose:
      - 3306
    env_file: .env
    volumes:
      - db:/var/lib/mysql
    networks:
      - docker-network

  wordpress:
    build: ./requirements/wordpress/
    env_file: .env
    volumes:
      - wordpress:/var/www/html
    networks:
      - docker-network

volumes:
  wordpress:

networks:
  docker-network:
    driver: bridge
