FROM	debian:buster 

RUN	apt-get update && apt-get install -y \
	mariadb-client \
	wget \
	php-mysql \ 
	php-mbstring \
	php7.3-fpm \
	php-cli \
	curl \
	sudo

# wp-cli 설치
RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && \
	chmod +x wp-cli.phar && \
	mv wp-cli.phar /usr/bin/wp

RUN mkdir /run/php

COPY	./tools/wordpress_setup.sh ./
COPY	./conf/www.conf /etc/php/7.3/fpm/pool.d/www.conf

WORKDIR	/var/www/html/wordpress

ENTRYPOINT	["bash", "/wordpress_setup.sh"]