FROM	debian:buster 

RUN	apt-get update && apt-get install -y \
	wget \
	php-mysql \ 
	php-mbstring \
	php7.3-fpm

COPY	./tools/wordpress_setup.sh ./
COPY	./conf/wp-config.php ./

ENTRYPOINT	["bash", "wordpress_setup.sh"]