FROM	debian:buster

LABEL	maintainer="sumsong@student.42seoul.kr"

RUN	apt-get update -y && apt-get upgrade -y

RUN	apt-get install -y \
	nginx \
	openssl

RUN	echo "daemon off;" >> /etc/nginx/nginx.conf

RUN	openssl req -newkey rsa:4096 -days 365 -nodes -x509 \
	-subj "/C=KR/ST=Seoul/L=Seoul/O=42Seoul/OU=Gam/CN=localhost" \
	-keyout /etc/ssl/private/localhost.dev.key \
	-out etc/ssl/certs/localhost.dev.crt && \
	chmod 600 etc/ssl/certs/localhost.dev.crt etc/ssl/private/localhost.dev.key

COPY	conf/default /etc/nginx/sites-available/

EXPOSE	443
