FROM	debian:buster

RUN	apt-get update -y && apt-get upgrade -y

RUN	apt-get install -y \
	nginx \
	openssl

# openssl 개인키, 공개키 생성
RUN	openssl req -newkey rsa:4096 -days 365 -nodes -x509 \
	-subj "/C=KR/ST=Seoul/L=Seoul/O=42Seoul/OU=Gam/CN=localhost" \
	-keyout /etc/ssl/private/localhost.dev.key \
	-out etc/ssl/certs/localhost.dev.crt && \
	chmod 600 etc/ssl/certs/localhost.dev.crt etc/ssl/private/localhost.dev.key

# nginx conf 파일 복사
COPY	conf/default /etc/nginx/sites-available/

# 443 포트를 연결할 예정이다, 라고 안내
EXPOSE	443

# 변하지 않을 명령어는 ENTRYPOINT에, 변경될 인수는 CMD에 넣는 것이 좋음
ENTRYPOINT	["nginx", "-g", "daemon off;"]
